# Site settings
title: "小草庐 | A Tiny House"
description: "Minimal Jekyll theme for storytellers"
baseurl: ""
url: "https://atinyhouse.github.io/"

# Author
author:
  name: "小草庐"
  url: "https://atinyhouse.github.io"
  email: "lucca.caolu@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
include:
  - _pages

# Permalinks
permalink: /:year-:month-:day/:title

# Pagination
paginate: 10

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag